# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171130_0101'),
        ('shop', '0002_auto_20171127_1706'),
    ]

    operations = [
    ]
