# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.CharField(default='Тут будет Ваше фото', max_length=350),
        ),
    ]
